### ISSUE TITLE
Toggle laptop screen off if lid is closed

### ISSUE THREAD

**Issue by lindhe** [lindhe/dotfiles#3]
Check this file for status: /proc/acpi/button/lid/LID/state

**Comment by ErikThorsell** [comment]
Nice! 

On October 15, 2019 10:06:15 PM GMT+02:00, "Andreas Lindhé" <notifications@github.com> wrote:
>Check this file for status: /proc/acpi/button/lid/LID/state
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lindhe/dotfiles/issues/3

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
